python3 helloworld.py "$@"
python3 oneliners.py "$@"
python3 ot.py "$@"
python3 unanimous.py "$@"
python3 parallelsort.py "$@"
python3 sort.py "$@"
python3 indextounitvector.py "$@"
python3 secretsanta.py "$@"
python3 id3gini.py "$@"
python3 lpsolver.py "$@"
python3 lpsolverfxp.py "$@"
python3 aes.py "$@" -1
python3 onewayhashchains.py -k2 "$@"
python3 elgamal.py -b2 -o3 "$@"
python3 dsa.py --no-barrier "$@"
